---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
        apt: name=apache2 update_cache=yes state=latest
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
